name: Deploy Pages

on:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          token: ${{secrets.TOKEN}}

      - name: Download Latest Version
        uses: dawidd6/action-download-artifact@v2
        with:
          name: github-pages
          path: dist/demo
          workflow: test.yml
          github_token: ${{secrets.TOKEN}}
          search_artifacts: true

      - name: Create TAR artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/demo

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
          token: ${{secrets.TOKEN}}
