name: Test Library

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - next

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Setup NODE
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check demo
        run: npm run type-check:demo

      - name: Type check lib
        run: npm run type-check:lib

      - name: Lint files
        id: syntax-pass
        run: npm run lint

      - name: Test demo and lib
        id: test-pass
        run: npm run test:ci

      - name: Build Github Pages
        id: pages-build
        run: npm run build:demo

      - name: Build NPM Library
        id: lib-build
        run: npm run build:lib

      - name: Save pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist/demo

      - name: Save pages artifact
        uses: actions/upload-artifact@v3
        id: uploaded-artifacts
        with:
          name: latest-lib
          path: dist/lib

